[package]
name = "gbemulator"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = "1.17.1"
eframe = {version = "0.28.1", features = ["wgpu"]}
egui = "0.28.1"
egui-wgpu = "0.28.1"
egui_extras = "0.28.1"
env_logger = "0.11.5"
log = "0.4.22"
paste = "1.0.15"
rfd = "0.14.1"
winit = "0.30.5"

