[package]
name = "gbemulator"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.28.1"
egui = "0.28.1"
egui_extras = "0.28.1"
env_logger = "0.11.5"
log = "0.4.22"
paste = "1.0.15"
rfd = "0.14.1"
winit = "0.30.5"
