[package]
name = "gbemulator"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.5"
log = "0.4.22"
glfw = "0.58.0"
pollster = "0.3.0"
wgpu = "22.1.0"
bytemuck = { version = "1.18.0", features = ["derive"] }
